version: 0.0

os: linux
files:
   - source: /index.html
     destination: /var/www/html
   - source: /images/hackathon.png
     destination: /var/www/html/images
permissions:
   - object: /var/www/html
     pattern: "**"
     owner: apache
     group: apache
     mode: 755
     type:
       - file
hooks:
   BeforeInstall:
   - location: scripts/install_dependencies.sh
     runas: root
   - location: scripts/start_server.sh
     runas: root
   AfterInstall:
   - location: scripts/stop_server.sh
     runas: root
